version: '3.1'

services:
  verdaccio:
    image: verdaccio/verdaccio
    container_name: "verdaccio"
    environment:
      - PUID=1000
      - PGID=1000
      - VERDACCIO_PORT=4873
      - VERDACCIO_USER_UID=1000
    ports:
      - "4873:4873"
    volumes:
      - "./storage:/verdaccio/storage/data"
