apiVersion: skaffold/v2beta20
kind: Config
deploy:
  kubeContext: minikube
  kubectl:
    manifests:
      - ./kubernetes/*
build:
  local:
    push: false
  artifacts:
    - image: auth
      context: auth
      custom:
        buildCommand: ../build/build.sh auth
        dependencies:
          paths: ["../build/Dockerfile.dev", .]
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    # - image: renderer
    #   context: renderer
    #   custom:
    #     buildCommand: ./buildrenderer.sh
    #   sync:
    #     manual:
    #       - src: "**/*.tsx"
    #         dest: .
    - image: tickets
      context: tickets
      custom:
        buildCommand: ../build/build.sh tickets
        dependencies:
          paths: ["../build/Dockerfile.dev", .]
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: expiration
      context: expiration
      custom:
        buildCommand: ../build/build.sh expiration
        dependencies:
          paths: ["../build/Dockerfile.dev", .]
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: orders
      context: orders
      custom:
        buildCommand: ../build/build.sh orders
        dependencies:
          paths: ["../build/Dockerfile.dev", .]
      sync:
        manual:
          - src: "src/**/*.tsx"
            dest: .
    - image: payments
      context: payments
      custom:
        buildCommand: ../build/build.sh payments
        dependencies:
          paths: ["../build/Dockerfile.dev", .]
      sync:
        manual:
          - src: "src/**/*.tsx"
            dest: .
