apiVersion: skaffold/v2beta3
kind: Config
deploy:
  kubeContext: minikube
  kubectl:
    manifests:
    - ./kubernetes/*      
build:
  local:
    push: false
  artifacts:
    - image: auth
      context: auth
      custom:
        buildCommand: ./buildauth.sh
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: renderer
      context: renderer
      custom:
        buildCommand: ./buildrenderer.sh
      sync:
        manual:
          - src: "**/*.tsx"
            dest: .
    - image: tickets
      context: tickets
      custom:
        buildCommand: ./buildtickets.sh
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: expiration
      context: expiration
      custom:
        buildCommand: ./buildexpiration.sh
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: orders
      context: orders
      custom:
        buildCommand: ./buildorders.sh
      sync:
        manual:
          - src: "src/**/*.tsx"
            dest: .
    - image: payments
      context: payments
      custom:
        buildCommand: ./buildpayments.sh
      sync:
        manual:
          - src: "src/**/*.tsx"
            dest: .
