apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msposts
  template:
    metadata:
      labels:
        app: msposts
    spec:
      containers:
        - name: msposts
          image: localhost:5000/msposts
      imagePullSecrets:
        - name: regcred
