apiVersion: skaffold/v2beta3
kind: Config
deploy:
  kubeContext: minikube
  kubectl:
    manifests:
      - ./kubernetes/*
build:
  local:
    push: false
  artifacts:
    - image: auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: renderer
      context: renderer
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "pages/**/*.tsx"
            dest: .
          - src: "components/**/*.tsx"
            dest: .
      
