name: tests-orders

# on:
#   pull_request:
#     paths:
#       - 'auth/**'
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run:
          echo "//scope.bytesafe.dev/r/default/:_authToken=${{secrets.BYTESAFE_TOKEN}}" > ~/.npmrc &&
          cd orders &&
          npm update @scope/common --registry https://scope.bytesafe.dev/r/default/ &&
          npm install --registry https://scope.bytesafe.dev/r/default/ &&
          npm run test:ci
