name: tests-orders

on:
  pull_request:
    paths:
      - 'auth/**'
jobs:
  build:
    runs-on: Ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.6.0'
      - run:
          echo "//165.227.148.157:4873/:_authToken=${{secrets.DO_TOKEN}}" > ~/.npmrc &&
          cd orders &&
          npm update @scope/common --registry http://165.227.148.157:4873 &&
          npm install --registry http://165.227.148.157:4873 --loglevel verbose &&
          npm run test:ci
