name: tests-payments

on:
  pull_request:
    paths:
      - 'auth/**'
jobs:
  build:
    runs-on: Ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.6.0'
      - run:
          echo "//scope.bytesafe.dev/r/default/:_authToken=${{secrets.BYTESAFE_TOKEN}}" > ~/.npmrc &&
          cd payments &&
          npm update @scope/common --registry https://scope.bytesafe.dev/r/default/ &&
          npm install --registry https://scope.bytesafe.dev/r/default/ &&
          npm run test:ci
        env:
          STRIPE_KEY: ${{ secrets.STRIPE_KEY }}